{
  "config": {
    "step": {
      "pick_implementation": {
        "title": "[%key:common::config_flow::title::oauth2_pick_implementation%]"
      },
      "reauth_confirm": {
        "title": "[%key:common::config_flow::title::reauth%]",
        "description": "The Fitbit integration needs to re-authenticate your account"
      },
      "auth": {
        "title": "Link Fitbit Account"
      }
    },
    "abort": {
      "already_configured": "[%key:common::config_flow::abort::already_configured_account%]",
      "already_in_progress": "[%key:common::config_flow::abort::already_in_progress%]",
      "cannot_connect": "[%key:common::config_flow::error::cannot_connect%]",
      "timeout_connect": "[%key:common::config_flow::error::timeout_connect%]",
      "oauth_error": "[%key:common::config_flow::abort::oauth2_error%]",
      "missing_configuration": "[%key:common::config_flow::abort::oauth2_missing_configuration%]",
      "reauth_successful": "[%key:common::config_flow::abort::reauth_successful%]",
      "invalid_access_token": "[%key:common::config_flow::error::invalid_access_token%]",
      "unknown": "[%key:common::config_flow::error::unknown%]",
      "wrong_account": "The user credentials provided do not match this Fitbit account."
    },
    "create_entry": {
      "default": "[%key:common::config_flow::create_entry::authenticated%]"
    }
  },
  "entity": {
    "sensor": {
      "battery": {
        "name": "Battery"
      }
    }
  },
  "issues": {
    "deprecated_yaml": {
      "title": "Fitbit YAML configuration is being removed",
      "description": "Configuring Fitbit in configuration.yaml is being removed in Home Assistant 2024.03.\n\nIf you have existing OAuth Application Credentials, they have been imported into the UI automatically. Remove the YAML configuration from your configuration.yaml file and restart Home Assistant to fix this issue."
    }
  }
}
